# -*- coding: utf-8 -*-
"""Dataset2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lUf-pfuFkPm_CqFaMnM84fLcEDXv9Uct
"""

# ===============================================================
# 🧩 1️⃣ Import Required Libraries
# ===============================================================
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, confusion_matrix, classification_report
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB, BernoulliNB
from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.svm import SVC
from xgboost import XGBClassifier

# ===============================================================
# 📥 2️⃣ Load the Dataset
# ===============================================================
file_path = "/dataa.csv"  # update path if needed
df = pd.read_csv(file_path)

print("=== Dataset Loaded ===")
print(f"Shape: {df.shape}")
print("\nFirst 5 rows:")
print(df.head())

# ===============================================================
# 🔍 3️⃣ Check for Missing Values
# ===============================================================
print("\nMissing values per column:")
print(df.isnull().sum())

# Drop missing rows if any
df = df.dropna()
print(f"\nAfter dropping missing rows: {df.shape}")

# ===============================================================
# 🎯 4️⃣ Identify Columns
# ===============================================================
target_col = 'RiskLevel'  # Ensure this matches your CSV column exactly

# Split features and target
X = df.drop(columns=[target_col])
y = df[target_col]

# ===============================================================
# 🔢 5️⃣ Encode Target Column (Low/Mid/High → 0/1/2)
# ===============================================================
mapping = {
    'low risk': 0, 'mid risk': 1, 'high risk': 2,
    'Low Risk': 0, 'Mid Risk': 1, 'High Risk': 2
}
y = y.map(mapping).fillna(y).astype(int)

print("\nEncoded target value counts:")
print(y.value_counts())

# ===============================================================
# ⚖️ 6️⃣ Normalize Only Numerical Columns
# ===============================================================
num_cols = X.select_dtypes(include=['float64', 'int64']).columns

scaler = MinMaxScaler()
X_scaled = X.copy()
X_scaled[num_cols] = scaler.fit_transform(X[num_cols])

print("\n=== Normalization Done ===")
print(X_scaled.head())

# ===============================================================
# 🔀 7️⃣ Split Dataset (70% Train, 30% Test)
# ===============================================================
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.3, stratify=y, random_state=42
)

print(f"\nTrain shape: {X_train.shape}, Test shape: {X_test.shape}")
print(f"Target distribution (train):\n{y_train.value_counts(normalize=True)}")

# ===============================================================
# 🤖 8️⃣ Define Models
# ===============================================================
models = {
    "Decision Tree": DecisionTreeClassifier(random_state=42),
    "MLP": MLPClassifier(hidden_layer_sizes=(64, 32), max_iter=1000, random_state=42),
    "SVM (RBF)": SVC(kernel='rbf', probability=True, random_state=42),
    "KNN": KNeighborsClassifier(),
    "LDA": LinearDiscriminantAnalysis(),
    "Logistic Regression": LogisticRegression(max_iter=1000, multi_class='multinomial', random_state=42),
    "AdaBoost": AdaBoostClassifier(random_state=42),
    "Gaussian NB": GaussianNB(),
    "Bernoulli NB": BernoulliNB(),
    "XGBoost": XGBClassifier(eval_metric='mlogloss', use_label_encoder=False, random_state=42)
}

# ===============================================================
# 📈 9️⃣ Train, Predict & Evaluate Each Model
# ===============================================================
results = []

for name, model in models.items():
    print("\n" + "="*80)
    print(f"Training & Evaluating: {name}")

    # Train
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    # Probability for ROC (some models support it, some don't)
    y_proba = model.predict_proba(X_test) if hasattr(model, "predict_proba") else None

    # Metrics
    acc = accuracy_score(y_test, y_pred)
    prec = precision_score(y_test, y_pred, average='weighted')
    rec = recall_score(y_test, y_pred, average='weighted')
    f1 = f1_score(y_test, y_pred, average='weighted')
    roc = roc_auc_score(y_test, y_proba, multi_class='ovr') if y_proba is not None else np.nan

    print(f"Accuracy: {acc:.4f} | Precision: {prec:.4f} | Recall: {rec:.4f} | F1: {f1:.4f} | ROC_AUC: {roc:.4f}")
    print("Confusion Matrix:")
    print(confusion_matrix(y_test, y_pred))
    print("Classification Report:")
    print(classification_report(y_test, y_pred))

    results.append([name, acc, prec, rec, f1, roc])

# ===============================================================
# 🧾 🔟 Summarize Model Performance
# ===============================================================
summary = pd.DataFrame(results, columns=["Model", "Accuracy", "Precision", "Recall", "F1", "ROC_AUC"])
summary = summary.sort_values(by="F1", ascending=False)

print("\n=== Summary of Model Performance ===")
print(summary)

summary.to_csv("model_performance_summary_multiclass.csv", index=False)
print("\n✅ Saved results to 'model_performance_summary_multiclass.csv'")

# ===============================================================
# 🔍 11️⃣ Feature Importance (Tree & Linear Models)
# ===============================================================
feature_importances = pd.DataFrame(index=X_train.columns)

# Train feature-importance-capable models
for model_name, model in [
    ("DecisionTree", DecisionTreeClassifier(random_state=42)),
    ("AdaBoost", AdaBoostClassifier(random_state=42)),
    ("XGBoost", XGBClassifier(eval_metric='mlogloss', use_label_encoder=False, random_state=42))
]:
    model.fit(X_train, y_train)
    feature_importances[model_name] = model.feature_importances_

# Logistic Regression absolute coefficients (averaged for multiclass)
lr = LogisticRegression(max_iter=1000, multi_class='multinomial', random_state=42)
lr.fit(X_train, y_train)
feature_importances["LogisticRegression(abs coef)"] = np.mean(np.abs(lr.coef_), axis=0)

# Sort by XGBoost importance
feature_importances = feature_importances.sort_values(by="XGBoost", ascending=False)

print("\n=== Feature Importances (Sorted by XGBoost) ===")
print(feature_importances.round(4))

feature_importances.to_csv("feature_importances_summary_multiclass.csv")
print("\n✅ Saved feature importances to 'feature_importances_summary_multiclass.csv'")

import pandas as pd

# Check the first few rows and columns
df = pd.read_csv("/content/dataa.csv")
print("=== Columns in your dataset ===")
print(df.columns.tolist())

print("\nFirst 3 rows:")
print(df.head(3))